baseURL = "http://example.org/"
languageCode = "en-us"
title = "TSite"
theme = "ananke"

[outputFormats.SearchIndex]
baseName = "search"
mediaType = "application/json"

[outputs]
home = [ "HTML", "RSS", "SearchIndex" ]

[params]
custom_css = ["lunr_search.css"]
custom_js = ["lunr_search.js"]
