baseURL = "http://example.org/"
languageCode = "en-us"
title = "TSite"
theme = "ananke"

[outputFormats.SearchIndex]
baseName = "search"
mediaType = "application/json"

[outputs]
home = [ "HTML", "RSS", "SearchIndex" ]
